# Lucia Configuration

server:
  port: 3000
  host: 0.0.0.0

store:
  trace:
    plugin: clickhouse
    config:
      host: localhost
      port: 8123
      database: hawk
      username: open-telemetry-ck
      password: "open-telemetry-ck-12345"

log:
  level: info
